### ISSUE TITLE
Does not build in Qt 5.9.x

### ISSUE THREAD

**Issue by Quipusrl** [kullo/qml-file-dialog-demo#5]
In Qt 5.9.x the project does not build.
The error is:
qml-file-dialog-demo/fileopendialog.cpp:11: error: no matching constructor for initialization of 'QFileDialogOptions'
    , m_options(QSharedPointer<QFileDialogOptions>(new QFileDialogOptions()))
